
// export const products = [
//     {
//         id: 1,
//         image: "./images/product1.png",
//         name: "Holanda Chocolate Creame",
//         weight: "542 g",
//         amount: "$3,000",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 2,
//         image: "./images/product2.png",
//         name: "Dasam Chocolate Creame",
//         weight: "1 L",
//         amount: "$2500",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 3,
//         image: "./images/product3.png",
//         name: "Dasam Chocolate Creame",
//         weight: "1 Kg",
//         amount: "$4600",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 4,
//         image: "./images/product4.png",
//         name: "Snickers Creame",
//         weight: "612 g",
//         amount: "$5000",
//         favorite: "./images/mdi_heart.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 5,
//         image: "./images/product5.png",
//         name: "Duetto Chocolate",
//         weight: "700 g",
//         amount: "$2,000",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 6,
//         image: "./images/product6.png",
//         name: "Nutella Chocolate Creame",
//         weight: "1 L ",
//         amount: "$1,000",
//         favorite: "./images/mdi_heart.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 7,
//         image: "./images/product7.png",
//         name: "Otanic Cream Chocolate",
//         weight: "542 g",
//         amount: "$3,000",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 8,
//         image: "./images/product8.png",
//         name: "Adorei Chocolate",
//         weight: "542 g",
//         amount: "$3,000",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 9,
//         image: "./images/product9.png",
//         name: "Laive Yopi Mix",
//         weight: "200 g",
//         amount: "$500",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 10,
//         image: "./images/product10.png",
//         name: "Pingo de leite Chocolate",
//         weight: "250 g",
//         amount: "$600",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 11,
//         image: "./images/product11.png",
//         name: "Nestle Nutren",
//         weight: "200 ml",
//         amount: "$200",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 12,
//         image: "./images/product12.png",
//         name: "Moni Chocolate Creame",
//         weight: "500 g",
//         amount: "$400",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 13,
//         image: "./images/product13.png",
//         name: "Nestle Classic",
//         weight: "150 ml",
//         amount: "$100",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 14,
//         image: "./images/product14.png",
//         name: "Neugebauer ",
//         weight: "300 ml",
//         amount: "$150",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 15,
//         image: "./images/product15.png",
//         name: "Pop Up Chocolate",
//         weight: "500 g",
//         amount: "$100",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 16,
//         image: "./images/product16.png",
//         name: "M&M’s Chocolate",
//         weight: "1 kg",
//         amount: "$200",
//         favorite: "./images/mdi_heart.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 17,
//         image: "./images/product17.png",
//         name: "Kopiko Coffee",
//         weight: "20 g",
//         amount: "$100",
//         favorite: "./images/mdi_heart.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 18,
//         image: "./images/product18.png",
//         name: "Aymore Chocolate ",
//         weight: "400 g",
//         amount: "$1500",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 19,
//         image: "./images/product19.png",
//         name: "Trento Speciale Avala",
//         weight: "400 g",
//         amount: "$150",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
//     {
//         id: 20,
//         image: "./images/product20.png",
//         name: "Melken Chocolate",
//         weight: "500 g",
//         amount: "$200",
//         favorite: "./images/favorite.png",
//         cart: "./images/mdi_cart-outline.png",
//     },
// ];


// src/products.ts

import { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    image: './images/product1.png',
    name: 'Holanda Chocolate Creame',
    weight: '542 g',
    amount: '$3,000',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Creamy chocolate delight from Holanda.',
    unique_id: 'holanda-chocolate-creame-542g',
    url_slug: 'holanda-chocolate-creame',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product1.png', position: 1 },
      { url: './images/product1-2.png', position: 2 },
    ],
    current_price: [{ NGN: [3000, 'anything', []] }],
    available_quantity: 10,
  },
  {
    id: '2',
    image: './images/product2.png',
    name: 'Dasam Chocolate Creame',
    weight: '1 L',
    amount: '$2,500',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Rich chocolate cream in a convenient 1 liter size.',
    unique_id: 'dasam-chocolate-creame-1l',
    url_slug: 'dasam-chocolate-creame',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product2.png', position: 1 },
      { url: './images/product2-2.png', position: 2 },
    ],
    current_price: [{ NGN: [2500, 'anything', []] }],
    available_quantity: 15,
  },
  {
    id: '3',
    image: './images/product3.png',
    name: 'Dasam Chocolate Creame',
    weight: '1 Kg',
    amount: '$4,600',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Premium quality chocolate cream in a 1 Kg pack.',
    unique_id: 'dasam-chocolate-creame-1kg',
    url_slug: 'dasam-chocolate-creame-1kg',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product3.png', position: 1 },
      { url: './images/product3-2.png', position: 2 },
    ],
    current_price: [{ NGN: [4600, 'anything', []] }],
    available_quantity: 8,
  },
  {
    id: '4',
    image: './images/product4.png',
    name: 'Snickers Creame',
    weight: '612 g',
    amount: '$5,000',
    favorite: './images/mdi_heart.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Delicious Snickers flavored chocolate cream.',
    unique_id: 'snickers-creame-612g',
    url_slug: 'snickers-creame',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product4.png', position: 1 },
      { url: './images/product4-2.png', position: 2 },
    ],
    current_price: [{ NGN: [5000, 'anything', []] }],
    available_quantity: 12,
  },
  {
    id: '5',
    image: './images/product5.png',
    name: 'Duetto Chocolate',
    weight: '700 g',
    amount: '$2,000',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Double delight chocolate treat with creamy texture.',
    unique_id: 'duetto-chocolate-700g',
    url_slug: 'duetto-chocolate',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product5.png', position: 1 },
      { url: './images/product5-2.png', position: 2 },
    ],
    current_price: [{ NGN: [2000, 'anything', []] }],
    available_quantity: 20,
  },
  {
    id: '6',
    image: './images/product6.png',
    name: 'Nutella Chocolate Creame',
    weight: '1 L',
    amount: '$1,000',
    favorite: './images/mdi_heart.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Classic Nutella flavor in a convenient 1 liter size.',
    unique_id: 'nutella-chocolate-creame-1l',
    url_slug: 'nutella-chocolate-creame',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product6.png', position: 1 },
      { url: './images/product6-2.png', position: 2 },
    ],
    current_price: [{ NGN: [1000, 'anything', []] }],
    available_quantity: 18,
  },
  {
    id: '7',
    image: './images/product7.png',
    name: 'Otanic Cream Chocolate',
    weight: '542 g',
    amount: '$3,000',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Exquisite Otanic cream blended with rich chocolate.',
    unique_id: 'otanic-cream-chocolate-542g',
    url_slug: 'otanic-cream-chocolate',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product7.png', position: 1 },
      { url: './images/product7-2.png', position: 2 },
    ],
    current_price: [{ NGN: [3000, 'anything', []] }],
    available_quantity: 14,
  },
  {
    id: '8',
    image: './images/product8.png',
    name: 'Adorei Chocolate',
    weight: '542 g',
    amount: '$3,000',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Adorei brand chocolate with a luxurious taste.',
    unique_id: 'adorei-chocolate-542g',
    url_slug: 'adorei-chocolate',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product8.png', position: 1 },
      { url: './images/product8-2.png', position: 2 },
    ],
    current_price: [{ NGN: [3000, 'anything', []] }],
    available_quantity: 16,
  },
  {
    id: '9',
    image: './images/product9.png',
    name: 'Laive Yopi Mix',
    weight: '200 g',
    amount: '$500',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Laive Yopi mix with assorted flavors.',
    unique_id: 'laive-yopi-mix-200g',
    url_slug: 'laive-yopi-mix',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product9.png', position: 1 },
      { url: './images/product9-2.png', position: 2 },
    ],
    current_price: [{ NGN: [500, 'anything', []] }],
    available_quantity: 25,
  },
  {
    id: '10',
    image: './images/product10.png',
    name: 'Pingo de leite Chocolate',
    weight: '250 g',
    amount: '$600',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Delicious Pingo de leite chocolate bars.',
    unique_id: 'pingo-de-leite-chocolate-250g',
    url_slug: 'pingo-de-leite-chocolate',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product10.png', position: 1 },
      { url: './images/product10-2.png', position: 2 },
    ],
    current_price: [{ NGN: [600, 'anything', []] }],
    available_quantity: 30,
  },
  {
    id: '11',
    image: './images/product11.png',
    name: 'Nestle Nutren',
    weight: '200 ml',
    amount: '$200',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Nutritional Nestle Nutren drink in 200 ml packs.',
    unique_id: 'nestle-nutren-200ml',
    url_slug: 'nestle-nutren',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product11.png', position: 1 },
      { url: './images/product11-2.png', position: 2 },
    ],
    current_price: [{ NGN: [200, 'anything', []] }],
    available_quantity: 40,
  },
  {
    id: '12',
    image: './images/product12.png',
    name: 'Moni Chocolate Creame',
    weight: '500 g',
    amount: '$400',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Moni brand chocolate cream in 500 g packs.',
    unique_id: 'moni-chocolate-creame-500g',
    url_slug: 'moni-chocolate-creame',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product12.png', position: 1 },
      { url: './images/product12-2.png', position: 2 },
    ],
    current_price: [{ NGN: [400, 'anything', []] }],
    available_quantity: 20,
  },
  {
    id: '13',
    image: './images/product13.png',
    name: 'Nestle Classic',
    weight: '150 ml',
    amount: '$100',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Classic Nestle chocolate in convenient 150 ml size.',
    unique_id: 'nestle-classic-150ml',
    url_slug: 'nestle-classic',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product13.png', position: 1 },
      { url: './images/product13-2.png', position: 2 },
    ],
    current_price: [{ NGN: [100, 'anything', []] }],
    available_quantity: 50,
  },
  {
    id: '14',
    image: './images/product14.png',
    name: 'Neugebauer',
    weight: '300 ml',
    amount: '$150',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Neugebauer chocolate in a refreshing 300 ml pack.',
    unique_id: 'neugebauer-300ml',
    url_slug: 'neugebauer',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product14.png', position: 1 },
      { url: './images/product14-2.png', position: 2 },
    ],
    current_price: [{ NGN: [150, 'anything', []] }],
    available_quantity: 30,
  },
  {
    id: '15',
    image: './images/product15.png',
    name: 'Pop Up Chocolate',
    weight: '500 g',
    amount: '$100',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Pop up your day with delicious chocolate bars.',
    unique_id: 'pop-up-chocolate-500g',
    url_slug: 'pop-up-chocolate',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product15.png', position: 1 },
      { url: './images/product15-2.png', position: 2 },
    ],
    current_price: [{ NGN: [100, 'anything', []] }],
    available_quantity: 25,
  },
  {
    id: '16',
    image: './images/product16.png',
    name: 'M&M’s Chocolate',
    weight: '1 kg',
    amount: '$200',
    favorite: './images/mdi_heart.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Colorful M&M\'s chocolate treats in a 1 kg pack.',
    unique_id: 'mms-chocolate-1kg',
    url_slug: 'mms-chocolate',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product16.png', position: 1 },
      { url: './images/product16-2.png', position: 2 },
    ],
    current_price: [{ NGN: [200, 'anything', []] }],
    available_quantity: 15,
  },
  {
    id: '17',
    image: './images/product17.png',
    name: 'Kopiko Coffee',
    weight: '20 g',
    amount: '$100',
    favorite: './images/mdi_heart.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Kopiko coffee candies in a convenient 20 g pack.',
    unique_id: 'kopiko-coffee-20g',
    url_slug: 'kopiko-coffee',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product17.png', position: 1 },
      { url: './images/product17-2.png', position: 2 },
    ],
    current_price: [{ NGN: [100, 'anything', []] }],
    available_quantity: 100,
  },
  {
    id: '18',
    image: './images/product18.png',
    name: 'Aymore Chocolate',
    weight: '400 g',
    amount: '$1,500',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Aymore brand chocolate bars in a 400 g pack.',
    unique_id: 'aymore-chocolate-400g',
    url_slug: 'aymore-chocolate',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product18.png', position: 1 },
      { url: './images/product18-2.png', position: 2 },
    ],
    current_price: [{ NGN: [1500, 'anything', []] }],
    available_quantity: 22,
  },
  {
    id: '19',
    image: './images/product19.png',
    name: 'Trento Speciale Avala',
    weight: '400 g',
    amount: '$150',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Trento Speciale Avala chocolate bars.',
    unique_id: 'trento-speciale-avala-400g',
    url_slug: 'trento-speciale-avala',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product19.png', position: 1 },
      { url: './images/product19-2.png', position: 2 },
    ],
    current_price: [{ NGN: [150, 'anything', []] }],
    available_quantity: 18,
  },
  {
    id: '20',
    image: './images/product20.png',
    name: 'Melken Chocolate',
    weight: '500 g',
    amount: '$200',
    favorite: './images/favorite.png',
    cart: './images/mdi_cart-outline.png',
    description: 'Melken brand chocolate bars in a 500 g pack.',
    unique_id: 'melken-chocolate-500g',
    url_slug: 'melken-chocolate',
    is_available: true,
    is_service: false,
    photos: [
      { url: './images/product20.png', position: 1 },
      { url: './images/product20-2.png', position: 2 },
    ],
    current_price: [{ NGN: [200, 'anything', []] }],
    available_quantity: 20,
  },
];

export default products;
