export const products = [
    {
        id: 1,
        image: "./images/product1.png",
        name: "Holanda Chocolate Creame",
        weight: "542 g",
        amount: "$3,000",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 2,
        image: "./images/product2.png",
        name: "Dasam Chocolate Creame",
        weight: "1 L",
        amount: "$2500",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 3,
        image: "./images/product3.png",
        name: "Dasam Chocolate Creame",
        weight: "1 Kg",
        amount: "$4600",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 4,
        image: "./images/product4.png",
        name: "Snickers Creame",
        weight: "612 g",
        amount: "$5000",
        favorite: "./images/mdi_heart.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 5,
        image: "./images/product5.png",
        name: "Duetto Chocolate",
        weight: "700 g",
        amount: "$2,000",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 6,
        image: "./images/product6.png",
        name: "Nutella Chocolate Creame",
        weight: "1 L ",
        amount: "$1,000",
        favorite: "./images/mdi_heart.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 7,
        image: "./images/product7.png",
        name: "Otanic Cream Chocolate",
        weight: "542 g",
        amount: "$3,000",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 8,
        image: "./images/product8.png",
        name: "Adorei Chocolate",
        weight: "542 g",
        amount: "$3,000",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 9,
        image: "./images/product9.png",
        name: "Laive Yopi Mix",
        weight: "200 g",
        amount: "$500",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 10,
        image: "./images/product10.png",
        name: "Pingo de leite Chocolate",
        weight: "250 g",
        amount: "$600",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 11,
        image: "./images/product11.png",
        name: "Nestle Nutren",
        weight: "200 ml",
        amount: "$200",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 12,
        image: "./images/product12.png",
        name: "Moni Chocolate Creame",
        weight: "500 g",
        amount: "$400",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 13,
        image: "./images/product13.png",
        name: "Nestle Classic",
        weight: "150 ml",
        amount: "$100",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 14,
        image: "./images/product14.png",
        name: "Neugebauer ",
        weight: "300 ml",
        amount: "$150",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 15,
        image: "./images/product15.png",
        name: "Pop Up Chocolate",
        weight: "500 g",
        amount: "$100",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 16,
        image: "./images/product16.png",
        name: "M&M’s Chocolate",
        weight: "1 kg",
        amount: "$200",
        favorite: "./images/mdi_heart.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 17,
        image: "./images/product17.png",
        name: "Kopiko Coffee",
        weight: "20 g",
        amount: "$100",
        favorite: "./images/mdi_heart.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 18,
        image: "./images/product18.png",
        name: "Aymore Chocolate ",
        weight: "400 g",
        amount: "$1500",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 19,
        image: "./images/product19.png",
        name: "Trento Speciale Avala",
        weight: "400 g",
        amount: "$150",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
    {
        id: 20,
        image: "./images/product20.png",
        name: "Melken Chocolate",
        weight: "500 g",
        amount: "$200",
        favorite: "./images/favorite.png",
        cart: "./images/mdi_cart-outline.png",
    },
];
